<?php

namespace WA\BoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DirectorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirectorsRepository extends EntityRepository
{
	// Le nombre de directors 
	public function getCountDirectors()
	{
		return $this->getEntityManager()
        			->createQuery(
                		'SELECT COUNT(d.id) FROM WABoBundle:Directors d'
            		)
            		->getSingleScalarResult();

	} 


}
