<?php

namespace WA\BoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserslRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserslRepository extends EntityRepository
{
}
